import Link from "next/link";
import Image from "next/image";
import { Building2, CalendarDays, Eye, GraduationCap, Handshake, Newspaper, Trophy } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getSession } from "@/server/auth/session";
import { getDashboardSummary, getDashboardTopPosts } from "@/server/queries/dashboard";

const cards = [
  ["Konten", "posts", Newspaper, "/admin/konten", "Kelola konten"], ["Guru & Staff", "guru", GraduationCap, "/admin/guru", "Kelola guru"], ["Mitra Industri", "partners", Handshake, "/admin/mitra-industri", "Kelola mitra"], ["Sarana & Prasarana", "facilities", Building2, "/admin/sarana-prasarana", "Kelola sarana"],
] as const;
export default async function AdminPage() {
  const session = await getSession();
  const summary = session && process.env.DATABASE_URL ? await getDashboardSummary(session) : { posts: 12, guru: 48, partners: 16, facilities: 24 };
  const topPosts = session && process.env.DATABASE_URL ? await getDashboardTopPosts(session) : [{ id: 1, title: "Selamat Datang di CibiOne CMS", type: "berita" as const, imageUrl: "/banner.jpeg", publishedAt: new Date(), viewCount: 1420, category: "Sekolah" }, { id: 2, title: "Prestasi Siswa SMKN 1 Cibinong", type: "prestasi" as const, imageUrl: "/smkn-hero-banner.png", publishedAt: new Date(), viewCount: 980, category: "Prestasi" }];
  const visible = session?.role === "jurusan_admin" ? cards.slice(0, 3) : cards;
  return <div className="mx-auto max-w-[1440px] space-y-8"><div><h1 className="text-2xl font-bold tracking-[-.03em]">Dashboard</h1><p className="mt-2 text-sm text-slate-500">Ringkasan konten yang dapat Anda kelola.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visible.map(([label, key, Icon, href, cta]) => <Card key={key} className="border-slate-200 shadow-[0_1px_2px_rgba(15,23,42,.05)]"><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-3"><CardTitle className="text-sm font-semibold text-slate-600">{label}</CardTitle><span className="grid size-10 place-items-center rounded-xl bg-[#E8F1F6] text-[#1D4F98]"><Icon className="size-5" /></span></CardHeader><CardContent><p className="tabular-nums text-3xl font-bold tracking-[-.04em]">{summary[key]}</p><Link href={href} className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-[#1D4F98] hover:underline">{cta} <span aria-hidden>→</span></Link></CardContent></Card>)}</div><Card><CardHeader className="flex-row items-center justify-between border-b"><div><CardTitle>Top posts</CardTitle><p className="mt-1 text-xs text-slate-500">Konten dengan views tertinggi.</p></div><Trophy className="size-5 text-[#1D4F98]" /></CardHeader><CardContent className="divide-y p-0">{topPosts.map((post, index) => <div key={post.id} className="grid gap-4 p-5 md:grid-cols-[180px_1fr_auto] md:items-center"><div className="relative aspect-[16/10] overflow-hidden rounded-xl bg-slate-100"><Image src={post.imageUrl ?? "/banner.jpeg"} alt={post.title} fill className="object-cover" sizes="180px" /></div><div><p className="text-xs font-semibold text-[#1D4F98]">#{index + 1} · {post.category ?? post.type}</p><h2 className="mt-1 font-bold">{post.title}</h2><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500"><span className="flex items-center gap-1"><CalendarDays className="size-3.5" />{post.publishedAt?.toLocaleDateString("id-ID") ?? "Draft"}</span><span className="flex items-center gap-1"><Eye className="size-3.5" />{post.viewCount.toLocaleString("id-ID")} views</span></div></div><Link href={`/admin/konten/${post.id}`} className="text-sm font-semibold text-[#1D4F98] hover:underline">Edit post →</Link></div>)}</CardContent></Card></div>;
}
